#! /usr/bin/env bash

# Test to see if $ZNCDATA is writable 
if [ ! -w "${ZNCDATA}" ]; then
  ZNCDATA=/var/tmp/znc-data
  export ZNCDATA
  mkdir ${ZNCDATA}
fi

# Create znc config if it doesn't exist
if [ ! -f "${ZNCDATA}/configs/znc.conf" ]; then
  mkdir "${ZNCDATA}/configs"
  cp /src/znc.conf.default "${ZNCDATA}/configs/znc.conf"
fi

if [ ! -f "${ZNCDATA}/znc.pem" ]; then
  znc --makepem -d "${ZNCDATA}"
fi

/usr/bin/znc -f -d ${ZNCDATA}
